name: 'Temp Kubernetes CI'
description: 'Run a Kubernetes cluster in your windows or linux CI VM'
branding:
  icon: download-cloud
  color: white
runs:
  using: 'node12'
  main: 'dist/index.js'